### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by amikai** [amikai/dotfiles#7]
- [ ] macOS preference
- [ ] chinese version Readme
- [ ] installation script include software update
- [ ] hammerspoon related file
- [ ] update the project layout (The project layout is too complicated now, so flatten the hierarchical structure)
